### ISSUE TITLE
2.0.1 Windows executable fatal error

### ISSUE THREAD

**Issue by jimbobshazham** [78Alpha/BMPMan#4]
Tried the new version with the windows executable and I'm getting 
![fatalerror](https://user-images.githubusercontent.com/5905572/55197869-d49fa300-51ab-11e9-9c1d-4131034fb636.PNG)
Can't give you any further info sorry

**Comment by 78Alpha** [comment]
That is honestly really strange...

I will have to do some more testing on windows it seems. it runs flawlessly on Unix... I will get back to you once I can make a guaranteed stable version.

**Comment by 78Alpha** [comment]
@jimbobshazham I identified the problem. It wasn't a code problem, but I found a work around. Apparently Python on Windows has a broken method of stripping text. So when it reads the BMP and removes the -number.bmp, it also removes the first and last letter of the file, so "magenta.zip" turned into "agenta.zi". I'll have to notify the python DEVs about that one. 

A new EXE can be found on teh prelease 2.0.2

https://github.com/78Alpha/BMPMan/releases/tag/2.0.2

Thank you for finding this, even if it wasn't intentional.
